# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a8e6d23d2ebbc33e8c52d05ec1532d792aef8c84d09998d2fffd2363727337433d8afb0ca844360bcec4edf2c11aac6a51e0b0b8fe8b1aaa06524802e5068c47

test:
  secret_key_base: ba725d05c552f9b0954b2001850aed6a4e490d4a5052950c3ef962439d5162aef555f0d8f1b5e6672841b24c1a8031789b19c67e7da9977bacbd80dc81058951

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
